load("//:build_defs.bzl", "cc_library")

cc_library(
    name = "tracefs",
    srcs = glob(["*.cpp"]),
    headers = glob(["*.h"]),
    header_namespace = "",
    deps = ["//src/util:util"],
    visibility = ["PUBLIC"],
)
