#define __KERNEL__
#include <stdbool.h>
#include <stddef.h>
#include <asm-generic/posix_types.h>
#include <asm/signal.h>
#include <bpf/bpf_helpers.h>

#define SIGNAL_ENUM(name, val) _##name = val

enum Signal {
  SIGNAL_ENUM(ABRT, SIGABRT),
  SIGNAL_ENUM(SIGABRT, SIGABRT),
  SIGNAL_ENUM(ALRM, SIGALRM),
  SIGNAL_ENUM(SIGALRM, SIGALRM),
  SIGNAL_ENUM(BUS, SIGBUS),
  SIGNAL_ENUM(SIGBUS, SIGBUS),
  SIGNAL_ENUM(CHLD, SIGCHLD),
  SIGNAL_ENUM(SIGCHLD, SIGCHLD),
  SIGNAL_ENUM(CONT, SIGCONT),
  SIGNAL_ENUM(SIGCONT, SIGCONT),
  SIGNAL_ENUM(FPE, SIGFPE),
  SIGNAL_ENUM(SIGFPE, SIGFPE),
  SIGNAL_ENUM(HUP, SIGHUP),
  SIGNAL_ENUM(SIGHUP, SIGHUP),
  SIGNAL_ENUM(ILL, SIGILL),
  SIGNAL_ENUM(SIGILL, SIGILL),
  SIGNAL_ENUM(INT, SIGINT),
  SIGNAL_ENUM(SIGINT, SIGINT),
  SIGNAL_ENUM(KILL, SIGKILL),
  SIGNAL_ENUM(SIGKILL, SIGKILL),
  SIGNAL_ENUM(PIPE, SIGPIPE),
  SIGNAL_ENUM(SIGPIPE, SIGPIPE),
  SIGNAL_ENUM(POLL, SIGPOLL),
  SIGNAL_ENUM(SIGPOLL, SIGPOLL),
  SIGNAL_ENUM(QUIT, SIGQUIT),
  SIGNAL_ENUM(SIGQUIT, SIGQUIT),
  SIGNAL_ENUM(SEGV, SIGSEGV),
  SIGNAL_ENUM(SIGSEGV, SIGSEGV),
  SIGNAL_ENUM(STOP, SIGSTOP),
  SIGNAL_ENUM(SIGSTOP, SIGSTOP),
  SIGNAL_ENUM(SYS, SIGSYS),
  SIGNAL_ENUM(SIGSYS, SIGSYS),
  SIGNAL_ENUM(TERM, SIGTERM),
  SIGNAL_ENUM(SIGTERM, SIGTERM),
  SIGNAL_ENUM(TRAP, SIGTRAP),
  SIGNAL_ENUM(SIGTRAP, SIGTRAP),
  SIGNAL_ENUM(TSTP, SIGTSTP),
  SIGNAL_ENUM(SIGTSTP, SIGTSTP),
  SIGNAL_ENUM(TTIN, SIGTTIN),
  SIGNAL_ENUM(SIGTTIN, SIGTTIN),
  SIGNAL_ENUM(TTOU, SIGTTOU),
  SIGNAL_ENUM(SIGTTOU, SIGTTOU),
  SIGNAL_ENUM(URG, SIGURG),
  SIGNAL_ENUM(SIGURG, SIGURG),
  SIGNAL_ENUM(USR1, SIGUSR1),
  SIGNAL_ENUM(SIGUSR1, SIGUSR1),
  SIGNAL_ENUM(USR2, SIGUSR2),
  SIGNAL_ENUM(SIGUSR2, SIGUSR2),
  SIGNAL_ENUM(VTALRM, SIGVTALRM),
  SIGNAL_ENUM(SIGVTALRM, SIGVTALRM),
  SIGNAL_ENUM(WINCH, SIGWINCH),
  SIGNAL_ENUM(SIGWINCH, SIGWINCH),
  SIGNAL_ENUM(XCPU, SIGXCPU),
  SIGNAL_ENUM(SIGXCPU, SIGXCPU),
  SIGNAL_ENUM(XFSZ, SIGXFSZ),
  SIGNAL_ENUM(SIGXFSZ, SIGXFSZ),
};

long __bpf_send_signal(enum Signal sig)
{
  return bpf_send_signal((__u32)sig);
}
